### ISSUE TITLE
KeyError: "Invalid board option 'upload.protocol'"

### ISSUE THREAD

**Issue by kalon33** [Ebiroll/RAK811_BreakBoard#6]
When following wiki instructions under Ubuntu 19.10 and Windows 10, I got this error in Platform.io, which prevent any build.

```
Warning! Ignore unknown configuration option `lib_dir` in section [env:rak811]
Warning! Ignore unknown configuration option `src_dir` in section [env:rak811]
Processing rak811 (platform: ststm32; board: rak811; framework: cmsis)
--------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter

  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 138, in cli
    is_test_running,
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\commands\run\command.py", line 170, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\commands\run\processor.py", line 80, in process
    result = p.run(build_vars, build_targets, self.silent, self.verbose, self.jobs)
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 383, in run
    self.configure_default_packages(options, targets)
  File "C:\Users\Nicolas\.platformio\platforms\ststm32\platform.py", line 34, in configure_default_packages
    "board")).get("upload.protocol") or ""
  File "c:\users\nicolas\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 731, in get
    raise KeyError("Invalid board option '%s'" % path)
KeyError: "Invalid board option 'upload.protocol'"
```
An idea how to fix this? I'm not used to Platform.io, so that might be trivial...

**Comment by Ebiroll** [comment]
Hello,
I have fixed the error in the rak811.json file now.
https://github.com/Ebiroll/RAK811_BreakBoard/commit/85dd1a84939d970246b339a6b45ca4cac4825bec
Note that the default board built is the wistrio, 
env_default = wistrio
https://github.com/RAKWireless/RAK5205-WisTrio-LoRa

**Comment by kalon33** [comment]
Thanks for your help. Now with Wistrio, it blocks at `OTAA Join Start` step. It is on EU868, and I provided Dev_EUI, AppEui and AppKey but nothing happen. I don't even see the LoRa packet in TTN console. Do you know why? If I move the board, I properly see the `ACC` lines

**Comment by Ebiroll** [comment]
Make sure you get all bytes correct, also with correct byteordering.
https://github.com/Ebiroll/RAK811_BreakBoard/blob/master/src/Commissioning.h
If OTAA does not work try, APB

https://os.mbed.com/teams/Semtech/code/LoRaWAN-NAMote72-Application-Demo/

**Comment by kalon33** [comment]
@Ebiroll I did not make use of the exact AppKey so it couldn't work... I noticed it a few minutes after posting sorry. Is it planned to make use of Wistrio integrated temperature/humidity/pressure/VOC sensor? Thanks again for your help, I finally could use and test my Wistrio properly thanks to you!
